#jinja2: newline_sequence:'\r\n'
{% if windows_version == '1709' %}
FROM microsoft/nanoserver:1709
{% else %}
FROM microsoft/nanoserver:latest
{% endif %}

# This is a base-Image for running Spring Boot Apps on Docker Windows Containers
MAINTAINER Jonas Hecht

# Extract Server-JRE into C:\\jdk1.8.0_xyz in the Container
ADD {{server_jre_name}} /

# Configure Path for easy Java usage
ENV JAVA_HOME=C:\\jdk1.8.0_{{java8_update_version}}
RUN setx PATH "%JAVA_HOME%\\bin;%PATH%"

# Create logging default path for Spring Boot
VOLUME C:\\tmp

{% if windows_version == 'pre-1709' %}
# A 'Temporary workaround for Windows DNS client weirdness' randomly found at https://github.com/docker/labs/blob/master/windows/windows-containers/MultiContainerApp.md
# Without this, DNS
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord
{% endif %}



