Vagrant.configure("2") do |config|

    # One Master / Manager Node with Linux
    config.vm.define "masterlinux" do |masterlinux|
        masterlinux.vm.box = "ubuntu/trusty64"
        masterlinux.vm.hostname = "masterlinux01"
        masterlinux.ssh.insert_key = false
        # Forwarding the port for Ansible explicitely to not run into Vagrants 'Port Collisions and Correction'
        # see https://www.vagrantup.com/docs/networking/forwarded_ports.html, which would lead to problems with Ansible later
        masterlinux.vm.network "forwarded_port", guest: 22, host: 2222, host_ip: "127.0.0.1", id: "ssh"

        # As to https://www.vagrantup.com/docs/multi-machine/ & https://www.vagrantup.com/docs/networking/private_network.html
        # we need to configure a private network, so that our machines are able to talk to one another
        masterlinux.vm.network "private_network", ip: "172.16.2.10"

        masterlinux.vm.provider :virtualbox do |virtualbox|
            virtualbox.name = "MasterLinuxUbuntu"
            virtualbox.gui = true
            virtualbox.memory = 1024
            virtualbox.cpus = 2
            virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
            virtualbox.customize ["modifyvm", :id, "--vram", "32"]
        end

        # Forwarding the Guest to Host ports, so that we can access it easily from outside the VM
        masterlinux.vm.network "forwarded_port", guest: 9000, host: 49000, host_ip: "127.0.0.1", id: "portainer"
        masterlinux.vm.network "forwarded_port", guest: 8080, host: 48080, host_ip: "127.0.0.1", id: "traefik_dashboard"
        masterlinux.vm.network "forwarded_port", guest: 80, host: 40080, host_ip: "127.0.0.1", id: "traefik"

        # Open App ports for access from outside the VM
        masterlinux.vm.network "forwarded_port", guest: 8761, host: 8761, host_ip: "127.0.0.1", id: "eureka"
        masterlinux.vm.network "forwarded_port", guest: 8090, host: 8090, host_ip: "127.0.0.1", id: "weatherbackend"
        masterlinux.vm.network "forwarded_port", guest: 8091, host: 8091, host_ip: "127.0.0.1", id: "weatherbockend"
        masterlinux.vm.network "forwarded_port", guest: 8095, host: 8095, host_ip: "127.0.0.1", id: "weatherservice"
    end

    # One Worker Node with Linux
    config.vm.define "workerlinux" do |workerlinux|
        workerlinux.vm.box = "ubuntu/trusty64"
        workerlinux.vm.hostname = "workerlinux01"
        workerlinux.ssh.insert_key = false
        # Forwarding the port for Ansible explicitely to not run into Vagrants 'Port Collisions and Correction'
        # see https://www.vagrantup.com/docs/networking/forwarded_ports.html, which would lead to problems with Ansible later
        workerlinux.vm.network "forwarded_port", guest: 22, host: 2232, host_ip: "127.0.0.1", id: "ssh"

        # As to https://www.vagrantup.com/docs/multi-machine/ & https://www.vagrantup.com/docs/networking/private_network.html
        # we need to configure a private network, so that our machines are able to talk to one another
        workerlinux.vm.network "private_network", ip: "172.16.2.11"

        workerlinux.vm.provider :virtualbox do |virtualbox|
            virtualbox.name = "WorkerLinuxUbuntu"
            virtualbox.gui = true
            virtualbox.memory = 1024
            virtualbox.cpus = 2
            virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
            virtualbox.customize ["modifyvm", :id, "--vram", "32"]
        end

        # Forwarding the Guest to Host ports, so that we can access it easily from outside the VM
        workerlinux.vm.network "forwarded_port", guest: 8080, host: 48081, host_ip: "127.0.0.1", id: "traefik_dashboard"
        workerlinux.vm.network "forwarded_port", guest: 80, host: 40081, host_ip: "127.0.0.1", id: "traefik"
    end

    # One Master / Manager Node with Windows Server 2016
    config.vm.define "masterwindows" do |masterwindows|
        masterwindows.vm.box = "windows_1709_docker_multimachine"
        masterwindows.vm.hostname = "masterwindows01"
        # Forwarding the port for Ansible explicitely to not run into Vagrants 'Port Collisions and Correction'
        # see https://www.vagrantup.com/docs/networking/forwarded_ports.html, which would lead to problems with Ansible later
        masterwindows.vm.network "forwarded_port", guest: 5986, host: 55986, host_ip: "127.0.0.1", id: "winrm-ssl"

        # As to https://www.vagrantup.com/docs/multi-machine/ & https://www.vagrantup.com/docs/networking/private_network.html
        # we need to configure a private network, so that our machines are able to talk to one another
        masterwindows.vm.network "private_network", ip: "172.16.2.12"

        masterwindows.vm.provider :virtualbox do |virtualbox|
            virtualbox.name = "MasterWindowsServer2016"
            virtualbox.gui = true
            virtualbox.memory = 2048
            virtualbox.cpus = 2
        end
        # Forwarding the Guest to Host ports, so that we can access it easily from outside the VM
        masterwindows.vm.network "forwarded_port", guest: 8080, host: 48082, host_ip: "127.0.0.1", id: "traefik_dashboard"
        masterwindows.vm.network "forwarded_port", guest: 80, host: 40082, host_ip: "127.0.0.1", id: "traefik"

        # Open App ports for access from outside the VM
        masterwindows.vm.network "forwarded_port", guest: 8761, host: 48761, host_ip: "127.0.0.1", id: "eureka"
        masterwindows.vm.network "forwarded_port", guest: 8090, host: 48090, host_ip: "127.0.0.1", id: "weatherbackend"
        masterwindows.vm.network "forwarded_port", guest: 8091, host: 48091, host_ip: "127.0.0.1", id: "weatherbockend"
        masterwindows.vm.network "forwarded_port", guest: 8095, host: 48095, host_ip: "127.0.0.1", id: "weatherservice"
    end

    # One Worker Node with Windows Server 2016
    config.vm.define "workerwindows" do |workerwindows|
        workerwindows.vm.box = "windows_1709_docker_multimachine"
        workerwindows.vm.hostname = "workerwindows01"
        # Forwarding the port for Ansible explicitely to not run into Vagrants 'Port Collisions and Correction'
        # see https://www.vagrantup.com/docs/networking/forwarded_ports.html, which would lead to problems with Ansible later
        workerwindows.vm.network "forwarded_port", guest: 5986, host: 55996, host_ip: "127.0.0.1", id: "winrm-ssl"

        # As to https://www.vagrantup.com/docs/multi-machine/ & https://www.vagrantup.com/docs/networking/private_network.html
        # we need to configure a private network, so that our machines are able to talk to one another
        workerwindows.vm.network "private_network", ip: "172.16.2.13"

        workerwindows.vm.provider :virtualbox do |virtualbox|
            virtualbox.name = "WorkerWindowsServer2016"
            virtualbox.gui = true
            virtualbox.memory = 2048
            virtualbox.cpus = 2
        end

        # Forwarding the Guest to Host ports, so that we can access it easily from outside the VM
        workerwindows.vm.network "forwarded_port", guest: 8080, host: 48083, host_ip: "127.0.0.1", id: "traefik_dashboard"
        workerwindows.vm.network "forwarded_port", guest: 80, host: 40083, host_ip: "127.0.0.1", id: "traefik"
    end

end