Vagrant.configure("2") do |config|

    # One Master / Manager Node with Windows Server 2016
    config.vm.define "masterwindows" do |masterwindows|
        masterwindows.vm.box = "windows_2016_multimachine"
        masterwindows.vm.hostname = "masterwindows01"

        # As to https://www.vagrantup.com/docs/multi-machine/ & https://www.vagrantup.com/docs/networking/private_network.html
        # we need to configure a private network, so that our machines are able to talk to one another
        masterwindows.vm.network "private_network", ip: "172.16.2.12"

        masterwindows.vm.provider :virtualbox do |virtualbox|
            virtualbox.name = "MasterWindowsServer2016"
            virtualbox.gui = true
            virtualbox.memory = 2048
            virtualbox.cpus = 2
        end

        # Forwarding the Windows Server 2016 Guest Port 8080 t0 48080
        # so that we can access it easily from outside the VM
        # config.vm.network "forwarded_port", guest: 8080, host: 48080, host_ip: "127.0.0.1", id: "edgeservice"
    end

    # One Master / Manager Node with Linux
    config.vm.define "masterlinux" do |masterlinux|
        masterlinux.vm.box = "ubuntu/trusty64"
        masterlinux.vm.hostname = "masterlinux01"
        masterlinux.ssh.insert_key = false

        # As to https://www.vagrantup.com/docs/multi-machine/ & https://www.vagrantup.com/docs/networking/private_network.html
        # we need to configure a private network, so that our machines are able to talk to one another
        masterlinux.vm.network "private_network", ip: "172.16.2.10"

        masterlinux.vm.provider :virtualbox do |virtualbox|
            virtualbox.name = "MasterLinuxUbuntu"
            virtualbox.gui = true
            virtualbox.memory = 2048
            virtualbox.cpus = 2
            virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
            virtualbox.customize ["modifyvm", :id, "--vram", "16"]
        end
    end

    # One Worker Node with Linux
    config.vm.define "workerlinux" do |workerlinux|
        workerlinux.vm.box = "ubuntu/trusty64"
        workerlinux.vm.hostname = "workerlinux01"
        workerlinux.ssh.insert_key = false

        # As to https://www.vagrantup.com/docs/multi-machine/ & https://www.vagrantup.com/docs/networking/private_network.html
        # we need to configure a private network, so that our machines are able to talk to one another
        workerlinux.vm.network "private_network", ip: "172.16.2.11"

        workerlinux.vm.provider :virtualbox do |virtualbox|
            virtualbox.name = "WorkerLinuxUbuntu"
            virtualbox.gui = true
            virtualbox.memory = 2048
            virtualbox.cpus = 2
            virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
            virtualbox.customize ["modifyvm", :id, "--vram", "16"]
        end
    end

    # One Worker Node with Windows Server 2016
    config.vm.define "workerwindows" do |workerwindows|
        workerwindows.vm.box = "windows_2016_multimachine"
        workerwindows.vm.hostname = "workerwindows01"

        # As to https://www.vagrantup.com/docs/multi-machine/ & https://www.vagrantup.com/docs/networking/private_network.html
        # we need to configure a private network, so that our machines are able to talk to one another
        workerwindows.vm.network "private_network", ip: "172.16.2.13"

        workerwindows.vm.provider :virtualbox do |virtualbox|
            virtualbox.name = "WorkerWindowsServer2016"
            virtualbox.gui = true
            virtualbox.memory = 2048
            virtualbox.cpus = 2
        end

        # Forwarding the Windows Server 2016 Guest Port 8080 t0 48080
        # so that we can access it easily from outside the VM
        # config.vm.network "forwarded_port", guest: 8080, host: 48080, host_ip: "127.0.0.1", id: "edgeservice"
    end

end