#jinja2: newline_sequence:'\r\n'
FROM springboot-oraclejre-nanoserver:latest

MAINTAINER Jonas Hecht

# Expose the apps Port
EXPOSE {{spring_boot_app.port}}

# Add Spring Boot app.jar to Container
ADD {{spring_boot_app.name}}.jar app.jar

# Fire up our Spring Boot app by default
CMD ["C:\\jdk1.8.0_{{java8_update_version}}\\bin\\java.exe", "-jar app.jar --server.port={{spring_boot_app.port}}"]

