#jinja2: newline_sequence:'\r\n'
FROM microsoft/windowsservercore:latest

# Expose the apps Port
EXPOSE 8080

# Extract Server-JRE into C:\\jdk1.8.0_121 in the Container
ADD server-jre-8u121-windows-x64.tar.gz /

# Create logging default path for Spring Boot
VOLUME C:\\tmp

# Add Spring Boot app.jar to Container
ADD {{spring_boot_app_name}}.jar app.jar

# Fire up our Spring Boot app by default
CMD ["C:\\jdk1.8.0_121\\bin\\java.exe", "-jar app.jar"]

