#jinja2: newline_sequence:'\r\n'
FROM microsoft/windowsservercore:latest

MAINTAINER Jonas Hecht

# Expose the apps Port
EXPOSE {{spring_boot_app.port}}

# Extract Server-JRE into C:\\jdk1.8.0_121 in the Container
ADD {{server_jre_name}} /

# Create logging default path for Spring Boot
VOLUME C:\\tmp

# Add Spring Boot app.jar to Container
ADD {{spring_boot_app_name}}.jar app.jar

# Fire up our Spring Boot app by default
CMD ["C:\\jdk1.8.0_{{java8_update_version}}\\bin\\java.exe", "-jar app.jar --server.port={{spring_boot_app.port}}"]

