#jinja2: newline_sequence:'\r\n'
FROM springboot-oraclejre-nanoserver:latest

MAINTAINER Jonas Hecht

ENV REGISTRY_HOST {{service_registry_name}}
ENV SPRINGBOOT_APP_NAME {{spring_boot_app.name}}

# Expose the apps Port
EXPOSE {{spring_boot_app.port}}

# Add Spring Boot app.jar to Container
ADD {{spring_boot_app.name}}.jar app.jar

# Fire up our Spring Boot app by default
CMD ["java.exe", "-jar app.jar --server.port={{spring_boot_app.port}}"]

