#jinja2: newline_sequence:'\r\n'
FROM windows-java:latest
VOLUME C:\\tmp
WORKDIR \spring-boot\{{spring_boot_app_name}}
ADD {{spring_boot_app_name}}.jar \spring-boot\{{spring_boot_app_name}}\app.jar
ENTRYPOINT ["java.exe -jar \spring-boot\{{spring_boot_app_name}}\app.jar"]