---
- hosts: all
  vars:
    application_stack_name: clearsky
    registry_host: 172.16.2.10:5000
    swarm_network_name: mixed_swarm_net
    base_path_windows: "C:\\springboot"
    base_path_linux: "/tmp/springboot"
    services:
      - name: zuul-edgeservice
        path_to_jar: "../../cxf-spring-cloud-netflix-docker/zuul-edgeservice/target/zuul-edgeservice-0.0.1-SNAPSHOT.jar"
        port: 8080
        map_to_same_port_on_host: true
        service_registry_name: eureka-serviceregistry
        deploy_target: windows

      - name: eureka-serviceregistry
        path_to_jar: "../../cxf-spring-cloud-netflix-docker/eureka-serviceregistry/target/eureka-serviceregistry-0.0.1-SNAPSHOT.jar"
        port: 8761
        map_to_same_port_on_host: true
        service_registry_name: eureka-serviceregistry-second
        deploy_target: windows

      - name: eureka-serviceregistry-second
        path_to_jar: "../../cxf-spring-cloud-netflix-docker/eureka-serviceregistry/target/eureka-serviceregistry-0.0.1-SNAPSHOT.jar"
        port: 8761
        service_registry_name: eureka-serviceregistry
        deploy_target: linux

      - name: weatherbackend
        path_to_jar: "../../cxf-spring-cloud-netflix-docker/weatherbackend/target/weatherbackend-0.0.1-SNAPSHOT.jar"
        port: 8090
        map_to_same_port_on_host: true
        service_registry_name: eureka-serviceregistry-second
        deploy_target: linux

      - name: weatherservice
        path_to_jar: "../../cxf-spring-cloud-netflix-docker/weatherservice/target/weatherservice-0.0.1-SNAPSHOT.jar"
        port: 8095
        map_to_same_port_on_host: true
        service_registry_name: eureka-serviceregistry
        deploy_target: windows

  tasks:

  - name: Create Docker build directory /tmp/springboot on Linux manager node, if not there
    file:
      path: "{{base_path_linux}}"
      state: directory
      mode: 0755
    when: inventory_hostname == "masterlinux01"

  - name: Create Docker build directory C:\springboot on Windows manager node, if not there
    win_file:
      path: "{{base_path_windows}}"
      state: directory
    when: inventory_hostname == "masterwindows01"

#  - name: Build Linux Apps Docker images on Linux manager node and push to Docker Swarm registry
#    include: prepare-docker-images-linux.yml
#    with_items: "{{ vars.services }}"
#    when: inventory_hostname == "masterlinux01" and item.deploy_target == 'linux'

#  - name: Build Windows Apps Docker images on Windows manager node and push to Docker Swarm registry
#    include: prepare-docker-images-windows.yml
#    with_items: "{{ vars.services }}"
#    when: inventory_hostname == "masterwindows01" and item.deploy_target == 'windows'

  - name: Open ports for Eureka discovery on TCP port 8761
    win_shell: "netsh firewall add portopening UDP 8761 'Port 8761'"
    when: inventory_hostname in groups['windows']

  - name: Deploy the Stack to the Swarm on Windows Manager node
    include: deploy-services-swarm.yml
    when: inventory_hostname == "masterwindows01"

#  - name: Do healthchecks for all services
#    include: spring-boot-app-health-check.yml
#    with_items: "{{ vars.services }}"